on:
  push:
    # delete this item if you don't want to trigger this workflow when modify this repo
    branches: main
name: Mirror GitHub Auto Queried Repos to Gitee
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/Josh-Jun
        dst: gitee/shijun_z
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: user
        force_update: true
        clone_style: ssh
        static_list: "sync2gitee"
